### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto#479] opened 2016-02-18 22:27 UTC
@lukeczapla reported this over on openworm/CElegansNeuroML#56 and I wanted to redirect here:

>Geppetto, OTOH, I have been having some major problems with. I installed the older Java 1.6 to fulfill the compatibility requirements, and it seems to load most of the code in the kernel and the Apache Tomcat server, but the org.geppetto.frontend fails out along with some other bundles and so I can't access the localhost site and play around with it to learn more. So on the end of trying to look at the code instead of the production alpha release- I have Eclipse and some other Java dev tools installed but it seems hard to find the git repository containing all the main code (unless I have to grab each module individually). Those are all issues that I've been having personally.

@lukeczapla, have you come across http://docs.geppetto.org ?  It sounds like perhaps you aren't finding good installation instructions yet?  Can you elaborate on what you are using to guide you here?

**Comment by lukeczapla** [comment] 2016-02-18 22:35
Hi Stephen, I followed these instructions and I'm on MacOS X: 

http://docs.geppetto.org/en/latest/install.html

I had previously had issues with OS X having buggy OpenCL drivers when using OpenMM, but I don't believe that has anything to do with my problem.  Here's just a snapshot of the last page of output from running Geppetto on the terminal (the log.log file does NOT elaborate any further) with my GEPPETTO_HOME and JAVA_HOME properly set (and it's pointing to the Home for Java 1.6.0_65).. previous pages show several other failures:







	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:132)
	at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStarted(StandardArtifactStateMonitor.java:271)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartSucceeded(AbstractInstallArtifact.java:319)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$0(AbstractInstallArtifact.java:316)
	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalSuccessfulCompletion(AbstractInstallArtifact.java:252)
	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:140)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.eclipse.gemini.web.core.WebApplicationStartFailedException: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/org.geppetto.frontend' failed to start. Check the logs for more details.
	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:137)
	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:122)
	... 8 common frames omitted
Caused by: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/org.geppetto.frontend' failed to start. Check the logs for more details.
	at org.eclipse.gemini.web.tomcat.internal.TomcatServletContainer.startWebApplication(TomcatServletContainer.java:133)
	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:109)
	... 9 common frames omitted

**Comment by tarelli** [comment] 2016-02-18 22:47
@slarson thanks for transferring the question. @lukeczapla hi Luke, sorry to hear you had some troubles. Java 6 is not a requirement and most of us are on Java 7 (and some are playing with Java 8 too which requires a newer version of Virgo), what pointed you to Java 6? Just in case we have some old docs  still around. Anyway, could you paste the whole log? Usually the exception you are pointing to has some underlying cause that can be understood by inspecting previous exceptions. Also FYI installing Geppetto locally isn't a requirement in many scenarios, for instance you can play with a snapshot of the muscle cell model at [this address ](https://live.geppetto.org/geppetto?load_project_from_id=4), I thought I'd mention it just in case.

**Comment by slarson** [comment] 2016-02-18 22:47
OK -- one thing I am seeing on the docs is it is saying Java 7 is now
required, but you are using Java 6, right?  Can you try Java 7 and see if
that helps?
ᐧ

**Comment by lukeczapla** [comment] 2016-02-18 22:58
Hi Tarelli and Stephen, I wanted to use Java 8 and I use that for my own work and for teaching; however, it fails the JavaVersionChecker test when launched.  Here's the output when I point the JAVA_HOME to the /Home folder for JDK 1.8, this geppetto output is much shorter:

JavaVersionChecker: Java version must be at 1.6 (detected version 1.8.0_60).


Can I get the newer version of Virgo and otherwise do I have to install Java 7 too?





Here's the whole log (renamed log.txt from log.log in serviceability/logs)!
[log.txt](https://github.com/openworm/org.geppetto/files/137109/log.txt)

**Comment by tarelli** [comment] 2016-02-18 23:04
This is the first exception which is responsible for the failure and indeed it is caused by Java 6.
`AG0000E Application context creation failure for bundle 'multi-artifact.plan-1-org.geppetto.model.swc' version '0.2.7'. org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.geppetto.model.swc.SWCModelInterpreterService] for bean with name 'SWCModelInterpreterService' defined in URL [file:/Users/luke/network/geppetto/work/deployer/s/multi-artifact.plan-1/2/0/model.swc-0.2.7.jar/org/geppetto/model/swc/SWCModelInterpreterService.class]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/geppetto/model/swc/SWCModelInterpreterService : Unsupported major.minor version 51.0
`
You can either install Java 7 as per instructions (my advice) or if you want to venture into uncharted territory and use Java 8 you'll have to install the newer version of Virgo 3.6.4, see [this](https://github.com/openworm/org.geppetto/issues/472). I'd like to move to the new Virgo as the default for the next release 0.2.9 due in about a month. Also from the log I noticed you have locally version 0.2.7, I would recommend using the latest version 0.2.8 which was merged to master just few days ago.

**Comment by lukeczapla** [comment] 2016-02-19 00:01
Thank you Dr. Cantarelli I am now using the master repo ( http://docs.geppetto.org/en/latest/osxlinuxsetup.html ) instead of the .zip/.tar.gz in the other instructions.


I ran into the following problems that are again attached, I am attempting what you described, using Virgo 3.6.4.  It seems like it can't find org.springframework.spring version 3.1.3; although I see a number of files, I don't see where that java code would be.  Here's what I found in the folder at least!  The log.log file from Virgo 3.6.4 is attached as log.txt and what was present for this module is pasted below.
[log.txt](https://github.com/openworm/org.geppetto/files/137192/log.txt)

./geppetto/repository/ext/org.springframework.spring-library-3.1.3.RELEASE.libd
./geppetto/repository/usr/org.springframework.spring-library-3.1.3.RELEASE.libd
./geppetto/work/deployer/s/multi-artifact.plan-1/4/0/org.geppetto.frontend.war/WEB-INF/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd
./org.geppetto.core/target/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd
./org.geppetto.frontend/target/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd
./org.geppetto.frontend/target/frontend-0.2.8/WEB-INF/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd
./org.geppetto.model.neuroml/target/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd
./org.geppetto.model.swc/target/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd
./org.geppetto.simulation/target/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd
./virgo-tomcat-server-3.6.4.RELEASE/repository/ext/org.springframework.spring-library_3.1.0.RELEASE.libd
./virgo-tomcat-server-3.6.4.RELEASE/work/deployer/s/multi-artifact.plan-1/5/0/org.geppetto.frontend.jar/WEB-INF/classes/lib/org.springframework.spring-library-3.1.3.RELEASE.libd

**Comment by tarelli** [comment] 2016-02-19 13:50
@lukeczapla I think the problem is that the 3.1.3 libd is missing from the right place. I just merged a PR https://github.com/openworm/org.geppetto/commit/7b2d9acd5cecdffd78e5d6b441d667b87523a412 which should take care of that. To try it checkout the dev version of org.geppetto and after doing mvn install redo update_server.py which should now copy the library to where it should be. I haven't tried myself as I'm still with the previous version but it's worth a shot otherwise I'll look into 3.6.4 as soon as I can, let me know either way!

**Comment by lukeczapla** [comment] 2016-02-19 16:01
thank you, I am now successful in connecting to and using the frontend!  I just copied the update_server.py and ran it and there are no problems at all during startup!  Thanks so much, problem solved and it's running with Virgo 3.6.4 and Java 1.8, and I have been able to open the project in eclipse to explore.

**Comment by tarelli** [comment] 2016-02-19 16:01
Great! Enjoy ;)

**Closed** 2016-02-19 16:01 UTC
Labels: in progress, question

**Comment by bupereira** [comment] 2016-12-14 14:42
@tarelli I just want to say thanks for posting this. Configuring my Virgo in my raspberry pi as I type this. Really helpful!

**Comment by tarelli** [comment] 2016-12-14 16:42
@bupereira glad it helped!
